FROM postgres:15.2-alpine

# Installing shadow to have access to usermod command to be able to block shell access to root.
RUN apk add --update --no-cache --virtual .build-deps shadow && \
    usermod -s /usr/sbin/nologin root && \
# Deleting the shadow package as it's job is done, and deleting the /var/cache/apk dir to have a slightly reduced image size.
    apk del .build-deps shadow && \
    rm -rf /var/cache/apk/* && \
# Changing ownership of "/var/lib/postgresql/data" to postgres user.
    chown -R postgres:postgres /var/lib/postgresql/data

# # A step for once I get deeper into databases.
COPY initdb.sh /docker-entrypoint-initdb.d/
RUN chmod +x /docker-entrypoint-initdb.d/initdb.sh

# Better than default of root.
USER postgres