resources:
  - ../../base
  - ../../base/django
  - ../../base/postgres
  - namespace.yaml

namespace: development

patchesStrategicMerge:
  - patches/django-deployment-patch.yaml
  - patches/postgres-deployment-patch.yaml

configMapGenerator:
  - name: django-envs
    envs:
      - envs/django.env
      - envs/shared/django_db.env

  - name: postgres-envs
    env: envs/shared/django_db.env

secretGenerator:
  - name: django-secrets
    envs:
      - secrets/django.secrets
      - secrets/shared/django_db.secrets

  - name: postgres-secrets
    env: secrets/postgres.secrets