resources:
  - ../../base
  - namespace.yaml

namespace: development

namePrefix: dev-

patchesStrategicMerge:
  - patches/nginx-deployment-patch.yaml
  - patches/postgres-deployment-patch.yaml

configMapGenerator:
  - name: django-env
    env: envs/django.env

secretGenerator:
  - name: django-secrets
    env: secrets/django.secrets
  
  - name: postgres-secrets
    env: secrets/postgres.secrets