apiVersion: v1
kind: PersistentVolume
metadata:
  name: django-static-files-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  local:
    path: /vol/django-static-files
