apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-web-deployment
  labels:
    app: django
spec:
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: localhost:5000/django-website
        envFrom:
          - secretRef:
              name: django-secrets
          - configMapRef:
              name: django-envs
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
      # volumes:
      #   - name: django-static-files
      #     persistentVolumeClaim:
      #       claimName: django-static-files-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: django-web-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: django