version: '3.9'

services:
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile.proxy
    container_name: proxy-server
    volumes:
      - web-static-data:/vol/web/static
      - gunicorn-socket-volume:/run/gunicorn
    environment:
      DOMAIN: localhost
    ports:
      - "80:80"
    depends_on:
      - web
    restart: unless-stopped
    networks:
      external-network:
        ipv4_address: 172.20.0.101

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.web
    container_name: django-server
    volumes:
      - web-static-data:/vol/web/static
      - gunicorn-socket-volume:/run/gunicorn
    env_file:
      - ./.shared_secrets/django_db.env
      - ./web/.env
    command: /opt/venv/bin/python /home/django/my-website-project/manage.py collectstatic --noinput
    depends_on:
      - db
      # - vault
    restart: unless-stopped
    networks:
      - external-network
      - internal-network

  db:
    build:
      context: ./db
      dockerfile: Dockerfile.db
    container_name: db-server
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ./.shared_secrets/django_db.env
      - ./db/.env
    restart: unless-stopped
    networks:
      - internal-network

  prometheus:
    build:
      context: ./prometheus
      dockerfile: Dockerfile.prometheus
    container_name: prometheus
    volumes:
      - prometheus-data:/prometheus/
    depends_on:
      - proxy
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      external-network:
        ipv4_address: 172.20.0.102
      internal-network:

  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile.grafana
    container_name: grafana
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - external-network
      - internal-network

networks:
  external-network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
  internal-network:
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24

volumes:
  gunicorn-socket-volume:
  web-static-data:
  db-data:
  prometheus-data:
  grafana-data: