global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: Django Monitoring
    metrics_path: /metrics
    static_configs:
      - targets:
        - proxy:80
  - job_name: Prometheus Monitoring
    metrics_path: /metrics
    static_configs:
      - targets:
        - host.docker.internal:9090