# Next step to configure.

FROM hashicorp/vault:latest

RUN useradd --create-home --shell /bin/bash vault && \
    chsh -s /usr/sbin/nologin root

COPY config.hcl /vault/config.d/config.hcl

ENTRYPOINT ["vault", "server", "-config=/vault/config/config.hcl"]
CMD ["audit-enable", "file", "file_path=/vault/file/audit.log"]